algoritmo "Nome do Programa"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : [Nome do Professor]
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : DATA_ATUAL/MES_ATUAL/ANO_ATUAL
var
numero: inteiro
//vetor[20]: inteiro

inicio

escreval("Escreva o numero: ")
leia(numero)
escreval(numero)
leia(numero)
escreval(numero)


escreval(numero[0])

fimalgoritmo